### ISSUE TITLE
[Bug Report] this.domNode.setAttribute is not a function

### ISSUE THREAD

**Issue by s1nc4pp** [ElemeFE/element#7315]
![err1](https://user-images.githubusercontent.com/1741988/31045438-74642ec8-a5ec-11e7-9d7b-327044e040ca.png)

### Element UI version
2.0.0-alpha.1

### OS/Browsers version
OSX/Chrome Version 61.0.3163.100 

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/584/](https://jsfiddle.net/pj71jkyw/584/)

### Steps to reproduce
I just upgraded to element 2.0.0

### What is Expected?
Working correctly 

### What is actually happening?
When i upgraded to element 2.0.0 it is working good but i also got error in the console "Error in mounted hook: "TypeError: this.domNode.setAttribute is not a function"
But this codes works in 1.4.6 with no error

**Comment by iwillwen** [comment]
+1, It seems like ElementUI@2.0 think the new-line(`#text` node) is an `el-menu-item`, actully it should clean them out.

**Comment by Leopoldthecoder** [comment]
Fixed in #7321
